// emojiNames.js - Emoji search database
const emojiNames = {
    // Smileys & Emotion
    '😀': ['grinning', 'face', 'smile', 'happy', 'joy'],
    '😃': ['grinning', 'face', 'happy', 'smile', 'joy'],
    '😄': ['grinning', 'face', 'happy', 'smile', 'joy'],
    '😁': ['grinning', 'face', 'happy', 'smile', 'joy'],
    '😆': ['grinning', 'face', 'happy', 'smile', 'laugh'],
    '😅': ['grinning', 'face', 'happy', 'smile', 'sweat'],
    '🤣': ['rolling', 'floor', 'laugh', 'funny', 'lol'],
    '😂': ['tears', 'joy', 'laugh', 'funny', 'lol'],
    '🙂': ['slightly', 'smiling', 'face', 'happy'],
    '🙃': ['upside', 'down', 'face', 'silly'],
    '😉': ['winking', 'face', 'flirt'],
    '😊': ['smiling', 'face', 'blush', 'happy'],
    '😇': ['smiling', 'face', 'halo', 'angel'],
    '🥰': ['smiling', 'face', 'hearts', 'love'],
    '😍': ['heart', 'eyes', 'love', 'crush'],
    '🤩': ['star', 'struck', 'excited'],
    '😘': ['face', 'blowing', 'kiss', 'love'],
    '😗': ['kissing', 'face', 'kiss'],
    '😚': ['kissing', 'face', 'closed', 'eyes'],
    '😙': ['kissing', 'face', 'smiling', 'eyes'],
    '😋': ['face', 'savoring', 'food', 'yum'],
    '😛': ['face', 'tongue', 'silly'],
    '😜': ['winking', 'face', 'tongue', 'silly'],
    '🤪': ['zany', 'face', 'crazy', 'silly'],
    '😝': ['squinting', 'face', 'tongue', 'silly'],
    '🤑': ['money', 'mouth', 'face', 'rich'],
    '🤗': ['hugging', 'face', 'hug', 'warm'],
    '🤭': ['face', 'hand', 'mouth', 'oops'],
    '🤫': ['shushing', 'face', 'quiet', 'secret'],
    '🤔': ['thinking', 'face', 'hmm', 'wonder'],
    '🤐': ['zipper', 'mouth', 'face', 'quiet'],
    '🤨': ['face', 'raised', 'eyebrow', 'suspicious'],
    '😐': ['neutral', 'face', 'meh'],
    '😑': ['expressionless', 'face', 'blank'],
    '😶': ['face', 'without', 'mouth', 'speechless'],
    '😏': ['smirking', 'face', 'smug'],
    '😒': ['unamused', 'face', 'bored'],
    '🙄': ['face', 'rolling', 'eyes', 'annoyed'],
    '😬': ['grimacing', 'face', 'awkward'],
    '🤥': ['lying', 'face', 'pinocchio'],
    '😔': ['pensive', 'face', 'sad'],
    '😪': ['sleepy', 'face', 'tired'],
    '🤤': ['drooling', 'face', 'hungry'],
    '😴': ['sleeping', 'face', 'sleep'],
    '😷': ['face', 'medical', 'mask', 'sick'],
    '🤒': ['face', 'thermometer', 'sick', 'fever'],
    '🤕': ['face', 'head', 'bandage', 'hurt'],
    '🤢': ['nauseated', 'face', 'sick', 'green'],
    '🤮': ['face', 'vomiting', 'sick', 'puke'],
    '🤧': ['sneezing', 'face', 'sick', 'achoo'],
    '🥵': ['hot', 'face', 'sweat', 'heat'],
    '🥶': ['cold', 'face', 'freeze', 'blue'],
    '🥴': ['woozy', 'face', 'dizzy', 'drunk'],
    '😵': ['dizzy', 'face', 'confused'],
    '🤯': ['exploding', 'head', 'mind', 'blown'],
    '🤠': ['cowboy', 'hat', 'face', 'western'],
    '🥳': ['partying', 'face', 'party', 'celebrate'],
    '😎': ['smiling', 'face', 'sunglasses', 'cool'],
    '🤓': ['nerd', 'face', 'glasses', 'geek'],
    '🧐': ['face', 'monocle', 'fancy', 'inspect'],
    '😕': ['confused', 'face', 'sad'],
    '😟': ['worried', 'face', 'concerned'],
    '🙁': ['slightly', 'frowning', 'face'],
    '😮': ['face', 'open', 'mouth', 'surprised'],
    '😯': ['hushed', 'face', 'surprised'],
    '😲': ['astonished', 'face', 'shocked'],
    '😳': ['flushed', 'face', 'embarrassed'],
    '🥺': ['pleading', 'face', 'puppy', 'eyes'],
    '😦': ['frowning', 'face', 'open', 'mouth'],
    '😧': ['anguished', 'face', 'worried'],
    '😨': ['fearful', 'face', 'scared'],
    '😰': ['anxious', 'face', 'worried'],
    '😥': ['sad', 'relieved', 'face'],
    '😢': ['crying', 'face', 'tear', 'sad'],
    '😭': ['loudly', 'crying', 'face', 'sob'],
    '😱': ['face', 'screaming', 'fear', 'scared'],
    '😖': ['confounded', 'face', 'frustrated'],
    '😣': ['persevering', 'face', 'struggle'],
    '😞': ['disappointed', 'face', 'sad'],
    '😓': ['downcast', 'face', 'sweat'],
    '😩': ['weary', 'face', 'tired'],
    '😫': ['tired', 'face', 'exhausted'],
    '🥱': ['yawning', 'face', 'sleepy'],
    '😤': ['face', 'steam', 'nose', 'angry'],
    '😡': ['pouting', 'face', 'angry', 'mad'],
    '😠': ['angry', 'face', 'mad'],
    '🤬': ['face', 'symbols', 'mouth', 'swearing'],
    '😈': ['smiling', 'face', 'horns', 'devil'],
    '👿': ['angry', 'face', 'horns', 'devil'],
    '💀': ['skull', 'death', 'dead'],
    '💩': ['pile', 'poo', 'poop'],
    '🤡': ['clown', 'face', 'circus'],
    '👹': ['ogre', 'monster', 'red'],
    '👺': ['goblin', 'monster', 'red'],
    '👻': ['ghost', 'spooky', 'boo'],
    '👽': ['alien', 'space', 'extraterrestrial'],
    '👾': ['alien', 'monster', 'game'],
    '🤖': ['robot', 'face', 'machine'],
    '😺': ['grinning', 'cat', 'face', 'happy'],
    '😸': ['grinning', 'cat', 'face', 'smile'],
    '😹': ['cat', 'face', 'tears', 'joy'],
    '😻': ['smiling', 'cat', 'face', 'heart', 'eyes'],
    '😼': ['cat', 'face', 'wry', 'smile'],
    '😽': ['kissing', 'cat', 'face'],
    '🙀': ['weary', 'cat', 'face', 'surprised'],
    '😿': ['crying', 'cat', 'face', 'sad'],
    '😾': ['pouting', 'cat', 'face', 'angry'],

    // People & Body
    '👋': ['waving', 'hand', 'hello', 'hi', 'bye'],
    '🤚': ['raised', 'back', 'hand', 'stop'],
    '🖐️': ['hand', 'fingers', 'splayed'],
    '✋': ['raised', 'hand', 'stop'],
    '🖖': ['vulcan', 'salute', 'spock'],
    '👌': ['ok', 'hand', 'perfect'],
    '🤞': ['crossed', 'fingers', 'luck'],
    '🤟': ['love', 'you', 'gesture'],
    '🤘': ['sign', 'horns', 'rock'],
    '🤙': ['call', 'hand', 'shaka'],
    '👈': ['backhand', 'index', 'pointing', 'left'],
    '👉': ['backhand', 'index', 'pointing', 'right'],
    '👆': ['backhand', 'index', 'pointing', 'up'],
    '🖕': ['middle', 'finger', 'rude'],
    '👇': ['backhand', 'index', 'pointing', 'down'],
    '👍': ['thumbs', 'up', 'like', 'good'],
    '👎': ['thumbs', 'down', 'dislike', 'bad'],
    '👊': ['oncoming', 'fist', 'punch'],
    '✊': ['raised', 'fist', 'power'],
    '🤛': ['left', 'facing', 'fist'],
    '🤜': ['right', 'facing', 'fist'],
    '👏': ['clapping', 'hands', 'applause'],
    '🙌': ['raising', 'hands', 'celebration'],
    '👐': ['open', 'hands', 'hug'],
    '🤲': ['palms', 'up', 'together'],
    '🤝': ['handshake', 'deal', 'agreement'],
    '🙏': ['folded', 'hands', 'pray', 'please'],
    '💅': ['nail', 'polish', 'beauty'],
    '🤳': ['selfie', 'camera', 'phone'],
    '💪': ['flexed', 'biceps', 'strong'],
    '🦾': ['mechanical', 'arm', 'prosthetic'],
    '🦿': ['mechanical', 'leg', 'prosthetic'],
    '🦵': ['leg', 'limb'],
    '🦶': ['foot', 'kick'],
    '👂': ['ear', 'listen', 'hear'],
    '🦻': ['ear', 'hearing', 'aid'],
    '👃': ['nose', 'smell'],
    '🧠': ['brain', 'smart', 'think'],
    '🦷': ['tooth', 'dentist'],
    '🦴': ['bone', 'skeleton'],
    '👀': ['eyes', 'look', 'see'],
    '👁️': ['eye', 'look', 'see'],
    '👅': ['tongue', 'taste'],
    '👄': ['mouth', 'lips'],
    '💋': ['kiss', 'mark', 'lipstick'],
    '🩸': ['drop', 'blood', 'red'],

    // Animals & Nature
    '🐶': ['dog', 'face', 'puppy', 'pet'],
    '🐱': ['cat', 'face', 'kitten', 'pet'],
    '🐭': ['mouse', 'face', 'rodent'],
    '🐹': ['hamster', 'face', 'pet'],
    '🐰': ['rabbit', 'face', 'bunny'],
    '🦊': ['fox', 'face', 'orange'],
    '🐻': ['bear', 'face', 'teddy'],
    '🐼': ['panda', 'face', 'black', 'white'],
    '🐨': ['koala', 'face', 'australia'],
    '🐯': ['tiger', 'face', 'stripes'],
    '🦁': ['lion', 'face', 'king'],
    '🐮': ['cow', 'face', 'moo'],
    '🐷': ['pig', 'face', 'oink'],
    '🐸': ['frog', 'face', 'green'],
    '🐵': ['monkey', 'face', 'banana'],
    '🐔': ['chicken', 'bird', 'farm'],
    '🐧': ['penguin', 'bird', 'cold'],
    '🐦': ['bird', 'fly'],
    '🐤': ['baby', 'chick', 'bird'],
    '🐣': ['hatching', 'chick', 'bird'],
    '🐥': ['front', 'facing', 'baby', 'chick'],
    '🦆': ['duck', 'bird', 'water'],
    '🦅': ['eagle', 'bird', 'america'],
    '🦉': ['owl', 'bird', 'night'],
    '🦇': ['bat', 'vampire', 'night'],
    '🐺': ['wolf', 'face', 'howl'],
    '🐗': ['boar', 'pig', 'wild'],
    '🐴': ['horse', 'face', 'farm'],
    '🦄': ['unicorn', 'face', 'rainbow'],
    '🐝': ['honeybee', 'bee', 'buzz'],
    '🐛': ['bug', 'insect', 'caterpillar'],
    '🦋': ['butterfly', 'insect', 'pretty'],
    '🐌': ['snail', 'slow', 'shell'],
    '🐞': ['lady', 'beetle', 'bug'],
    '🐜': ['ant', 'insect', 'work'],
    '🦟': ['mosquito', 'insect', 'bite'],
    '🦗': ['cricket', 'insect', 'chirp'],
    '🕷️': ['spider', 'insect', 'web'],
    '🕸️': ['spider', 'web', 'net'],
    '🦂': ['scorpion', 'desert', 'sting'],
    '🐢': ['turtle', 'slow', 'shell'],
    '🐍': ['snake', 'reptile', 'slither'],
    '🦎': ['lizard', 'gecko', 'reptile'],
    '🦖': ['t-rex', 'dinosaur', 'extinct'],
    '🦕': ['sauropod', 'dinosaur', 'extinct'],
    '🐙': ['octopus', 'sea', 'tentacles'],
    '🦑': ['squid', 'sea', 'tentacles'],
    '🦐': ['shrimp', 'sea', 'food'],
    '🦞': ['lobster', 'sea', 'food'],
    '🦀': ['crab', 'sea', 'food'],
    '🐡': ['blowfish', 'fish', 'sea'],
    '🐠': ['tropical', 'fish', 'sea'],
    '🐟': ['fish', 'sea', 'water'],
    '🐬': ['dolphin', 'sea', 'smart'],
    '🐳': ['spouting', 'whale', 'sea'],
    '🐋': ['whale', 'sea', 'big'],
    '🦈': ['shark', 'sea', 'teeth'],
    '🐊': ['crocodile', 'reptile', 'water'],

    // Food & Drink
    '🍏': ['green', 'apple', 'fruit', 'healthy'],
    '🍎': ['red', 'apple', 'fruit', 'healthy'],
    '🍐': ['pear', 'fruit', 'green'],
    '🍊': ['tangerine', 'orange', 'fruit'],
    '🍋': ['lemon', 'fruit', 'sour'],
    '🍌': ['banana', 'fruit', 'yellow'],
    '🍉': ['watermelon', 'fruit', 'summer'],
    '🍇': ['grapes', 'fruit', 'wine'],
    '🍓': ['strawberry', 'fruit', 'berry'],
    '🫐': ['blueberries', 'fruit', 'berry'],
    '🍈': ['melon', 'fruit', 'green'],
    '🍒': ['cherries', 'fruit', 'red'],
    '🍑': ['peach', 'fruit', 'fuzzy'],
    '🥭': ['mango', 'fruit', 'tropical'],
    '🍍': ['pineapple', 'fruit', 'tropical'],
    '🥥': ['coconut', 'fruit', 'tropical'],
    '🥝': ['kiwi', 'fruit', 'green'],
    '🍅': ['tomato', 'fruit', 'red'],
    '🍆': ['eggplant', 'vegetable', 'purple'],
    '🥑': ['avocado', 'fruit', 'green'],
    '🥦': ['broccoli', 'vegetable', 'green'],
    '🥬': ['leafy', 'greens', 'lettuce'],
    '🥒': ['cucumber', 'vegetable', 'green'],
    '🌶️': ['hot', 'pepper', 'spicy'],
    '🫑': ['bell', 'pepper', 'vegetable'],
    '🌽': ['corn', 'vegetable', 'yellow'],
    '🥕': ['carrot', 'vegetable', 'orange'],
    '🫒': ['olive', 'fruit', 'oil'],
    '🧄': ['garlic', 'vegetable', 'strong'],
    '🧅': ['onion', 'vegetable', 'cry'],
    '🥔': ['potato', 'vegetable', 'starch'],
    '🍠': ['roasted', 'sweet', 'potato'],
    '🥐': ['croissant', 'bread', 'french'],
    '🥯': ['bagel', 'bread', 'round'],
    '🍞': ['bread', 'loaf', 'wheat'],
    '🥖': ['baguette', 'bread', 'french'],
    '🥨': ['pretzel', 'bread', 'twisted'],
    '🧀': ['cheese', 'wedge', 'dairy'],
    '🥚': ['egg', 'protein', 'breakfast'],
    '🍳': ['cooking', 'egg', 'fried'],
    '🧈': ['butter', 'dairy', 'spread'],
    '🥞': ['pancakes', 'breakfast', 'syrup'],
    '🧇': ['waffle', 'breakfast', 'syrup'],
    '🥓': ['bacon', 'meat', 'breakfast'],
    '🥩': ['cut', 'meat', 'steak'],
    '🍗': ['poultry', 'leg', 'chicken'],
    '🍖': ['meat', 'bone', 'food'],
    '🦴': ['bone', 'skeleton', 'dog'],
    '🌭': ['hot', 'dog', 'sausage'],
    '🍔': ['hamburger', 'burger', 'meat'],
    '🍟': ['french', 'fries', 'potato'],
    '🍕': ['pizza', 'slice', 'cheese'],
    '🥪': ['sandwich', 'bread', 'lunch'],
    '🥙': ['stuffed', 'flatbread', 'wrap'],
    '🧆': ['falafel', 'middle', 'eastern'],
    '🌮': ['taco', 'mexican', 'food'],
    '🌯': ['burrito', 'wrap', 'mexican'],
    '🫔': ['tamale', 'mexican', 'food'],
    '🥗': ['green', 'salad', 'healthy'],
    '🥘': ['shallow', 'pan', 'food'],
    '🫕': ['fondue', 'cheese', 'pot'],
    '🥫': ['canned', 'food', 'tin'],
    '🍝': ['spaghetti', 'pasta', 'italian'],
    '🍜': ['steaming', 'bowl', 'noodles'],
    '🍲': ['pot', 'food', 'stew'],
    '🍛': ['curry', 'rice', 'indian'],
    '🍣': ['sushi', 'japanese', 'fish'],
    '🍱': ['bento', 'box', 'japanese'],
    '🥟': ['dumpling', 'chinese', 'food'],
    '🦪': ['oyster', 'shellfish', 'sea'],
    '🍤': ['fried', 'shrimp', 'seafood'],
    '🍙': ['rice', 'ball', 'japanese'],
    '🍚': ['cooked', 'rice', 'asian'],
    '🍘': ['rice', 'cracker', 'japanese'],
    '🍥': ['fish', 'cake', 'swirl'],
    '🥠': ['fortune', 'cookie', 'chinese'],
    '🥮': ['moon', 'cake', 'chinese'],
    '🍢': ['oden', 'japanese', 'skewer'],
    '🍡': ['dango', 'japanese', 'sweet'],
    '🍧': ['shaved', 'ice', 'dessert'],
    '🍨': ['ice', 'cream', 'dessert'],
    '🍦': ['soft', 'ice', 'cream'],
    '🥧': ['pie', 'dessert', 'sweet'],
    '🧁': ['cupcake', 'dessert', 'sweet'],
    '🍰': ['shortcake', 'dessert', 'sweet'],
    '🎂': ['birthday', 'cake', 'celebration'],
    '🍮': ['custard', 'dessert', 'sweet'],
    '🍭': ['lollipop', 'candy', 'sweet'],
    '🍬': ['candy', 'sweet', 'wrapper'],
    '🍫': ['chocolate', 'bar', 'sweet'],
    '🍿': ['popcorn', 'movie', 'snack'],
    '🍩': ['doughnut', 'donut', 'sweet'],
    '🍪': ['cookie', 'biscuit', 'sweet'],
    '🌰': ['chestnut', 'nut', 'fall'],
    '🥜': ['peanuts', 'nuts', 'snack'],
    '🍯': ['honey', 'pot', 'sweet'],
    '🥛': ['glass', 'milk', 'dairy'],
    '🍼': ['baby', 'bottle', 'milk'],
    '🫖': ['teapot', 'tea', 'drink'],
    '☕': ['hot', 'beverage', 'coffee'],
    '🍵': ['teacup', 'without', 'handle'],
    '🧃': ['beverage', 'box', 'juice'],
    '🥤': ['cup', 'straw', 'drink'],
    '🧋': ['bubble', 'tea', 'drink'],
    '🍶': ['sake', 'bottle', 'cup'],
    '🍺': ['beer', 'mug', 'alcohol'],
    '🍻': ['clinking', 'beer', 'mugs'],
    '🥂': ['clinking', 'glasses', 'champagne'],
    '🍷': ['wine', 'glass', 'alcohol'],
    '🥃': ['tumbler', 'glass', 'whiskey'],
    '🍸': ['cocktail', 'glass', 'drink'],
    '🍹': ['tropical', 'drink', 'cocktail'],
    '🧉': ['mate', 'drink', 'south', 'american'],
    '🍾': ['bottle', 'popping', 'cork'],

    // Travel & Places
    '🚗': ['automobile', 'car', 'vehicle'],
    '🚕': ['taxi', 'car', 'yellow'],
    '🚙': ['sport', 'utility', 'vehicle'],
    '🚌': ['bus', 'vehicle', 'public'],
    '🚎': ['trolleybus', 'bus', 'electric'],
    '🏎️': ['racing', 'car', 'fast'],
    '🚓': ['police', 'car', 'emergency'],
    '🚑': ['ambulance', 'emergency', 'medical'],
    '🚒': ['fire', 'engine', 'emergency'],
    '🚐': ['minibus', 'van', 'vehicle'],
    '🛻': ['pickup', 'truck', 'vehicle'],
    '🚚': ['delivery', 'truck', 'vehicle'],
    '🚛': ['articulated', 'lorry', 'truck'],
    '🚜': ['tractor', 'farm', 'vehicle'],
    '🏍️': ['motorcycle', 'bike', 'vehicle'],
    '🛵': ['motor', 'scooter', 'vehicle'],
    '🚲': ['bicycle', 'bike', 'pedal'],
    '🛴': ['kick', 'scooter', 'vehicle'],
    '🛹': ['skateboard', 'sport', 'board'],
    '🛼': ['roller', 'skate', 'sport'],
    '🚁': ['helicopter', 'aircraft', 'rotor'],
    '🛸': ['flying', 'saucer', 'ufo'],
    '✈️': ['airplane', 'aircraft', 'plane'],
    '🛩️': ['small', 'airplane', 'aircraft'],
    '🛫': ['airplane', 'departure', 'takeoff'],
    '🛬': ['airplane', 'arrival', 'landing'],
    '🪂': ['parachute', 'skydiving', 'fall'],
    '💺': ['seat', 'airplane', 'chair'],
    '🚀': ['rocket', 'space', 'launch'],
    '🛰️': ['satellite', 'space', 'orbit'],
    '🚉': ['station', 'train', 'platform'],
    '🚊': ['tram', 'trolley', 'streetcar'],
    '🚝': ['monorail', 'train', 'elevated'],
    '🚞': ['mountain', 'railway', 'train'],
    '🚋': ['tram', 'car', 'streetcar'],
    '🚃': ['railway', 'car', 'train'],
    '🚄': ['high', 'speed', 'train'],
    '🚅': ['bullet', 'train', 'fast'],
    '🚈': ['light', 'rail', 'train'],
    '🚂': ['locomotive', 'train', 'steam'],
    '🚆': ['train', 'railway', 'transport'],
    '🚇': ['metro', 'subway', 'underground'],
    '🚟': ['suspension', 'railway', 'monorail'],
    '🚠': ['mountain', 'cableway', 'cable'],
    '🚡': ['aerial', 'tramway', 'cable'],
    '🛶': ['canoe', 'boat', 'water'],
    '🚤': ['speedboat', 'boat', 'fast'],
    '🛥️': ['motor', 'boat', 'water'],
    '🛳️': ['passenger', 'ship', 'cruise'],
    '⛵': ['sailboat', 'boat', 'wind'],
    '🚢': ['ship', 'boat', 'ocean'],
    '⚓': ['anchor', 'boat', 'ship'],
    '🪝': ['hook', 'fishing', 'catch'],
    '⛽': ['fuel', 'pump', 'gas'],
    '🚧': ['construction', 'work', 'barrier'],
    '🚨': ['police', 'car', 'light'],
    '🚥': ['horizontal', 'traffic', 'light'],
    '🚦': ['vertical', 'traffic', 'light'],
    '🛑': ['stop', 'sign', 'octagon'],
    '🚏': ['bus', 'stop', 'sign'],
    '🗺️': ['world', 'map', 'geography'],
    '🗿': ['moai', 'easter', 'island'],
    '🗽': ['statue', 'liberty', 'america'],
    '🗼': ['tokyo', 'tower', 'japan'],
    '🏰': ['castle', 'fortress', 'medieval'],
    '🏯': ['japanese', 'castle', 'pagoda'],
    '🏟️': ['stadium', 'sports', 'arena'],
    '🎡': ['ferris', 'wheel', 'amusement'],
    '🎢': ['roller', 'coaster', 'amusement'],
    '🎠': ['carousel', 'horse', 'merry'],
    '⛲': ['fountain', 'water', 'park'],
    '⛱️': ['umbrella', 'beach', 'sun'],
    '🏖️': ['beach', 'umbrella', 'sand'],
    '🏝️': ['desert', 'island', 'tropical'],
    '🏜️': ['desert', 'sand', 'hot'],
    '🌋': ['volcano', 'eruption', 'lava'],
    '⛰️': ['mountain', 'peak', 'high'],
    '🏔️': ['snow', 'capped', 'mountain'],
    '🗻': ['mount', 'fuji', 'japan'],
    '🏕️': ['camping', 'tent', 'outdoor'],
    '⛺': ['tent', 'camping', 'outdoor'],
    '🏠': ['house', 'home', 'building'],
    '🏡': ['house', 'garden', 'home'],
    '🏘️': ['houses', 'buildings', 'neighborhood'],
    '🏚️': ['derelict', 'house', 'abandoned'],
    '🏗️': ['building', 'construction', 'crane'],
    '🏭': ['factory', 'industrial', 'smoke'],
    '🏢': ['office', 'building', 'business'],
    '🏬': ['department', 'store', 'shopping'],
    '🏣': ['japanese', 'post', 'office'],
    '🏤': ['post', 'office', 'european'],
    '🏥': ['hospital', 'medical', 'health'],
    '🏦': ['bank', 'money', 'finance'],
    '🏨': ['hotel', 'accommodation', 'travel'],
    '🏪': ['convenience', 'store', 'shop'],
    '🏫': ['school', 'education', 'learning'],
    '🏩': ['love', 'hotel', 'heart'],
    '💒': ['wedding', 'marriage', 'ceremony'],
    '🏛️': ['classical', 'building', 'government'],
    '⛪': ['church', 'christian', 'religion'],
    '🕌': ['mosque', 'islam', 'religion'],
    '🕍': ['synagogue', 'jewish', 'religion'],
    '🛕': ['hindu', 'temple', 'religion'],
    '🕋': ['kaaba', 'mecca', 'islam'],
    '⛩️': ['shinto', 'shrine', 'japan'],
    '🛤️': ['railway', 'track', 'train'],
    '🛣️': ['motorway', 'highway', 'road'],
    '🗾': ['map', 'japan', 'country'],
    '🎑': ['moon', 'viewing', 'ceremony'],
    '🏞️': ['national', 'park', 'nature'],
    '🌅': ['sunrise', 'morning', 'sun'],
    '🌄': ['sunrise', 'mountains', 'morning'],
    '🌠': ['shooting', 'star', 'night'],
    '🎇': ['sparkler', 'fireworks', 'celebration'],
    '🎆': ['fireworks', 'celebration', 'explosion'],
    '🌇': ['sunset', 'city', 'buildings'],
    '🌆': ['cityscape', 'dusk', 'buildings'],
    '🏙️': ['cityscape', 'buildings', 'urban'],
    '🌃': ['night', 'stars', 'city'],
    '🌌': ['milky', 'way', 'galaxy'],
    '🌉': ['bridge', 'night', 'water'],
    '🌁': ['foggy', 'weather', 'mist'],

    // Activities
    '⚽': ['soccer', 'ball', 'football'],
    '🏀': ['basketball', 'ball', 'sport'],
    '🏈': ['american', 'football', 'sport'],
    '⚾': ['baseball', 'ball', 'sport'],
    '🥎': ['softball', 'ball', 'sport'],
    '🎾': ['tennis', 'ball', 'sport'],
    '🏐': ['volleyball', 'ball', 'sport'],
    '🏉': ['rugby', 'football', 'sport'],
    '🥏': ['flying', 'disc', 'frisbee'],
    '🎱': ['pool', '8', 'ball'],
    '🪀': ['yo-yo', 'toy', 'string'],
    '🏓': ['ping', 'pong', 'table', 'tennis'],
    '🏸': ['badminton', 'racquet', 'sport'],
    '🏒': ['ice', 'hockey', 'stick'],
    '🏑': ['field', 'hockey', 'stick'],
    '🥍': ['lacrosse', 'stick', 'sport'],
    '🏏': ['cricket', 'bat', 'sport'],
    '🪃': ['boomerang', 'throw', 'return'],
    '🥅': ['goal', 'net', 'sport'],
    '⛳': ['flag', 'hole', 'golf'],
    '🪁': ['kite', 'wind', 'fly'],
    '🏹': ['bow', 'arrow', 'archery'],
    '🎣': ['fishing', 'pole', 'catch'],
    '🤿': ['diving', 'mask', 'underwater'],
    '🥊': ['boxing', 'glove', 'fight'],
    '🥋': ['martial', 'arts', 'uniform'],
    '🎽': ['running', 'shirt', 'sport'],
    '🛹': ['skateboard', 'sport', 'board'],
    '🛷': ['sled', 'snow', 'winter'],
    '⛸️': ['ice', 'skate', 'winter'],
    '🥌': ['curling', 'stone', 'sport'],
    '🎿': ['skis', 'snow', 'winter'],
    '⛷️': ['skier', 'snow', 'winter'],
    '🏂': ['snowboarder', 'snow', 'winter'],
    '🪂': ['parachute', 'skydiving', 'fall'],
    '🏋️': ['person', 'lifting', 'weights'],
    '🤸': ['person', 'cartwheeling', 'gymnastics'],
    '🤼': ['people', 'wrestling', 'sport'],
    '🤽': ['person', 'playing', 'water', 'polo'],
    '🤾': ['person', 'playing', 'handball'],
    '🧘': ['person', 'lotus', 'position'],
    '🏃': ['person', 'running', 'exercise'],
    '🚴': ['person', 'biking', 'cycling'],
    '🧗': ['person', 'climbing', 'rock'],
    '🧙': ['mage', 'wizard', 'magic'],
    '🎯': ['direct', 'hit', 'bullseye'],
    '🪀': ['yo-yo', 'toy', 'string'],
    '🎳': ['bowling', 'pins', 'strike'],
    '🎮': ['video', 'game', 'controller'],
    '🕹️': ['joystick', 'game', 'arcade'],
    '🎰': ['slot', 'machine', 'gambling'],
    '🎲': ['game', 'die', 'dice'],
    '🧩': ['puzzle', 'piece', 'jigsaw'],
    '🃏': ['joker', 'card', 'wild'],
    '🀄': ['mahjong', 'red', 'dragon'],
    '🎴': ['flower', 'playing', 'cards'],
    '🎭': ['performing', 'arts', 'theater'],
    '🖼️': ['framed', 'picture', 'art'],
    '🎨': ['artist', 'palette', 'paint'],
    '🧵': ['thread', 'sewing', 'needle'],
    '🪡': ['sewing', 'needle', 'thread'],
    '🧶': ['yarn', 'knitting', 'wool'],
    '🪢': ['knot', 'rope', 'tie'],

    // Objects
    '⌚': ['watch', 'time', 'wrist'],
    '📱': ['mobile', 'phone', 'smartphone'],
    '📲': ['mobile', 'phone', 'arrow'],
    '💻': ['laptop', 'computer', 'pc'],
    '⌨️': ['keyboard', 'computer', 'type'],
    '🖥️': ['desktop', 'computer', 'monitor'],
    '🖨️': ['printer', 'computer', 'paper'],
    '🖱️': ['computer', 'mouse', 'click'],
    '🖲️': ['trackball', 'computer', 'mouse'],
    '🕹️': ['joystick', 'game', 'controller'],
    '🗜️': ['clamp', 'tool', 'vise'],
    '💽': ['computer', 'disk', 'minidisc'],
    '💾': ['floppy', 'disk', 'save'],
    '💿': ['optical', 'disk', 'cd'],
    '📀': ['dvd', 'disk', 'movie'],
    '📼': ['videocassette', 'tape', 'vhs'],
    '📷': ['camera', 'photo', 'picture'],
    '📸': ['camera', 'flash', 'photo'],
    '📹': ['video', 'camera', 'record'],
    '🎥': ['movie', 'camera', 'film'],
    '📽️': ['film', 'projector', 'movie'],
    '🎞️': ['film', 'frames', 'movie'],
    '📞': ['telephone', 'receiver', 'call'],
    '☎️': ['telephone', 'phone', 'call'],
    '📟': ['pager', 'communication', 'beep'],
    '📠': ['fax', 'machine', 'document'],
    '📺': ['television', 'tv', 'screen'],
    '📻': ['radio', 'music', 'broadcast'],
    '🎙️': ['studio', 'microphone', 'record'],
    '🎚️': ['level', 'slider', 'audio'],
    '🎛️': ['control', 'knobs', 'audio'],
    '🧭': ['compass', 'navigation', 'direction'],
    '⏱️': ['stopwatch', 'timer', 'time'],
    '⏲️': ['timer', 'clock', 'countdown'],
    '⏰': ['alarm', 'clock', 'wake'],
    '🕰️': ['mantelpiece', 'clock', 'time'],
    '⏳': ['hourglass', 'flowing', 'sand'],
    '⌛': ['hourglass', 'done', 'time'],
    '📡': ['satellite', 'antenna', 'communication'],
    '🔋': ['battery', 'power', 'energy'],
    '🔌': ['electric', 'plug', 'power'],
    '💡': ['light', 'bulb', 'idea'],
    '🔦': ['flashlight', 'torch', 'light'],
    '🕯️': ['candle', 'flame', 'light'],
    '🪔': ['diya', 'lamp', 'oil'],
    '🧯': ['fire', 'extinguisher', 'safety'],
    '🛢️': ['oil', 'drum', 'barrel'],
    '💸': ['money', 'wings', 'flying'],
    '💵': ['dollar', 'banknote', 'money'],
    '💴': ['yen', 'banknote', 'money'],
    '💶': ['euro', 'banknote', 'money'],
    '💷': ['pound', 'banknote', 'money'],
    '🪙': ['coin', 'money', 'currency'],
    '💰': ['money', 'bag', 'dollar'],
    '💳': ['credit', 'card', 'payment'],
    '💎': ['gem', 'stone', 'diamond'],
    '⚖️': ['balance', 'scale', 'justice'],
    '🦯': ['white', 'cane', 'accessibility'],
    '🧰': ['toolbox', 'tools', 'repair'],
    '🔧': ['wrench', 'tool', 'repair'],
    '🔨': ['hammer', 'tool', 'nail'],
    '⚒️': ['hammer', 'pick', 'tools'],
    '🛠️': ['hammer', 'wrench', 'tools'],
    '⛏️': ['pick', 'tool', 'mining'],
    '🔩': ['nut', 'bolt', 'hardware'],
    '⚙️': ['gear', 'settings', 'mechanical'],
    '🧱': ['brick', 'building', 'wall'],
    '⛓️': ['chains', 'link', 'metal'],
    '🧲': ['magnet', 'attraction', 'horseshoe'],
    '🔫': ['water', 'pistol', 'gun'],
    '💣': ['bomb', 'explosive', 'danger'],
    '🧨': ['firecracker', 'explosive', 'dynamite'],
    '🪓': ['axe', 'tool', 'wood'],
    '🔪': ['kitchen', 'knife', 'cut'],
    '🗡️': ['dagger', 'knife', 'weapon'],
    '⚔️': ['crossed', 'swords', 'battle'],
    '🛡️': ['shield', 'protection', 'defense'],
    '🚬': ['cigarette', 'smoking', 'tobacco'],
    '⚰️': ['coffin', 'death', 'funeral'],
    '🪦': ['headstone', 'grave', 'cemetery'],
    '⚱️': ['funeral', 'urn', 'ashes'],
    '🏺': ['amphora', 'jar', 'ancient'],
    '🔮': ['crystal', 'ball', 'fortune'],
    '📿': ['prayer', 'beads', 'religion'],
    '🧿': ['nazar', 'amulet', 'evil', 'eye'],
    '💈': ['barber', 'pole', 'haircut'],
    '⚗️': ['alembic', 'distilling', 'chemistry'],
    '🔭': ['telescope', 'stars', 'astronomy'],
    '🔬': ['microscope', 'science', 'lab'],
    '🕳️': ['hole', 'opening', 'void'],
    '🩹': ['adhesive', 'bandage', 'first', 'aid'],
    '🩺': ['stethoscope', 'doctor', 'medical'],
    '💊': ['pill', 'medicine', 'health'],
    '💉': ['syringe', 'injection', 'medical'],
    '🩸': ['drop', 'blood', 'red'],
    '🧬': ['dna', 'genetics', 'biology'],
    '🦠': ['microbe', 'virus', 'bacteria'],
    '🧫': ['petri', 'dish', 'bacteria'],
    '🧪': ['test', 'tube', 'experiment'],
    '🌡️': ['thermometer', 'temperature', 'heat'],
    '🧹': ['broom', 'cleaning', 'sweep'],
    '🧽': ['sponge', 'cleaning', 'absorb'],
    '🚽': ['toilet', 'bathroom', 'wc'],
    '🚿': ['shower', 'water', 'bath'],
    '🛁': ['bathtub', 'bath', 'relax'],
    '🛀': ['person', 'taking', 'bath'],
    '🧴': ['lotion', 'bottle', 'moisturizer'],
    '🧷': ['safety', 'pin', 'diaper'],
    '🧸': ['teddy', 'bear', 'toy'],
    '🧻': ['roll', 'paper', 'toilet'],
    '🪒': ['razor', 'shaving', 'blade'],
    '🧼': ['soap', 'bar', 'cleaning'],
    '🪥': ['toothbrush', 'dental', 'hygiene'],
    '🪶': ['feather', 'bird', 'light'],
    '🧽': ['sponge', 'cleaning', 'kitchen'],
    '🧯': ['fire', 'extinguisher', 'safety'],
    '🛒': ['shopping', 'cart', 'trolley'],

    // Symbols
    '❤️': ['red', 'heart', 'love'],
    '🧡': ['orange', 'heart', 'love'],
    '💛': ['yellow', 'heart', 'love'],
    '💚': ['green', 'heart', 'love'],
    '💙': ['blue', 'heart', 'love'],
    '💜': ['purple', 'heart', 'love'],
    '🖤': ['black', 'heart', 'love'],
    '🤍': ['white', 'heart', 'love'],
    '🤎': ['brown', 'heart', 'love'],
    '💔': ['broken', 'heart', 'love'],
    '❣️': ['heart', 'exclamation', 'love'],
    '💕': ['two', 'hearts', 'love'],
    '💞': ['revolving', 'hearts', 'love'],
    '💓': ['beating', 'heart', 'love'],
    '💗': ['growing', 'heart', 'love'],
    '💖': ['sparkling', 'heart', 'love'],
    '💘': ['heart', 'arrow', 'love'],
    '💝': ['heart', 'ribbon', 'love'],
    '💟': ['heart', 'decoration', 'love'],
    '☮️': ['peace', 'symbol', 'hippie'],
    '✝️': ['latin', 'cross', 'christian'],
    '☪️': ['star', 'crescent', 'islam'],
    '🕉️': ['om', 'hinduism', 'buddhism'],
    '☸️': ['wheel', 'dharma', 'buddhism'],
    '✡️': ['star', 'david', 'judaism'],
    '🔯': ['dotted', 'six', 'pointed', 'star'],
    '🕎': ['menorah', 'judaism', 'candles'],
    '☯️': ['yin', 'yang', 'balance'],
    '☦️': ['orthodox', 'cross', 'christian'],
    '🛐': ['place', 'worship', 'religion'],
    '⛎': ['ophiuchus', 'zodiac', 'serpent'],
    '♈': ['aries', 'zodiac', 'ram'],
    '♉': ['taurus', 'zodiac', 'bull'],
    '♊': ['gemini', 'zodiac', 'twins'],
    '♋': ['cancer', 'zodiac', 'crab'],
    '♌': ['leo', 'zodiac', 'lion'],
    '♍': ['virgo', 'zodiac', 'maiden'],
    '♎': ['libra', 'zodiac', 'scales'],
    '♏': ['scorpio', 'zodiac', 'scorpion'],
    '♐': ['sagittarius', 'zodiac', 'archer'],
    '♑': ['capricorn', 'zodiac', 'goat'],
    '♒': ['aquarius', 'zodiac', 'water'],
    '♓': ['pisces', 'zodiac', 'fish'],
    '🆔': ['id', 'button', 'identification'],
    '⚛️': ['atom', 'symbol', 'science'],
    '🉑': ['japanese', 'acceptable', 'button'],
    '☢️': ['radioactive', 'danger', 'nuclear'],
    '☣️': ['biohazard', 'danger', 'toxic'],
    '📴': ['mobile', 'phone', 'off'],
    '📳': ['vibration', 'mode', 'phone'],
    '🈶': ['japanese', 'not', 'free', 'charge'],
    '🈚': ['japanese', 'free', 'charge', 'button'],
    '🈸': ['japanese', 'application', 'button'],
    '🈺': ['japanese', 'open', 'business', 'button'],
    '🈷️': ['japanese', 'monthly', 'amount', 'button'],
    '✴️': ['eight', 'pointed', 'star'],
    '🆚': ['vs', 'button', 'versus'],
    '💮': ['white', 'flower', 'japanese'],
    '🉐': ['japanese', 'bargain', 'button'],
    '㊙️': ['japanese', 'secret', 'button'],
    '㊗️': ['japanese', 'congratulations', 'button'],
    '🈴': ['japanese', 'passing', 'grade', 'button'],
    '🈵': ['japanese', 'no', 'vacancy', 'button'],
    '🈹': ['japanese', 'discount', 'button'],
    '🈲': ['japanese', 'prohibited', 'button'],
    '🅰️': ['button', 'blood', 'type'],
    '🅱️': ['button', 'blood', 'type'],
    '🆎': ['ab', 'button', 'blood', 'type'],
    '🆑': ['cl', 'button', 'clear'],
    '🅾️': ['button', 'blood', 'type'],
    '🆘': ['sos', 'button', 'help'],
    '❌': ['cross', 'mark', 'x'],
    '⭕': ['hollow', 'red', 'circle'],
    '🛑': ['stop', 'sign', 'octagon'],
    '⛔': ['no', 'entry', 'prohibited'],
    '📛': ['name', 'badge', 'identification'],
    '🚫': ['prohibited', 'not', 'allowed'],
    '💯': ['hundred', 'points', 'symbol'],
    '💢': ['anger', 'symbol', 'comic'],
    '♨️': ['hot', 'springs', 'steam'],
    '🚷': ['no', 'pedestrians', 'prohibited'],
    '🚯': ['no', 'littering', 'prohibited'],
    '🚳': ['no', 'bicycles', 'prohibited'],
    '🚱': ['non', 'potable', 'water'],
    '🔞': ['no', 'one', 'under', 'eighteen'],
    '📵': ['no', 'mobile', 'phones'],
    '🚭': ['no', 'smoking', 'prohibited'],
    '❗': ['exclamation', 'mark', 'heavy'],
    '❕': ['exclamation', 'mark', 'white'],
    '❓': ['question', 'mark', 'red'],
    '❔': ['question', 'mark', 'white'],
    '‼️': ['double', 'exclamation', 'mark'],
    '⁉️': ['exclamation', 'question', 'mark'],
    '🔅': ['low', 'brightness', 'symbol'],
    '🔆': ['high', 'brightness', 'symbol'],
    '〽️': ['part', 'alternation', 'mark'],
    '⚠️': ['warning', 'sign', 'caution'],
    '🚸': ['children', 'crossing', 'school'],
    '🔱': ['trident', 'emblem', 'symbol'],
    '⚜️': ['fleur', 'de', 'lis'],
    '🔰': ['japanese', 'symbol', 'beginner'],
    '♻️': ['recycling', 'symbol', 'green'],
    '✅': ['check', 'mark', 'button'],
    '🈯': ['japanese', 'reserved', 'button'],
    '💹': ['chart', 'increasing', 'yen'],
    '❇️': ['sparkle', 'symbol', 'star'],
    '✳️': ['eight', 'spoked', 'asterisk'],
    '❎': ['cross', 'mark', 'button'],
    '🌐': ['globe', 'meridians', 'internet'],
    '💠': ['diamond', 'blue', 'shape'],
    'Ⓜ️': ['circled', 'latin', 'capital', 'letter'],
    '🌀': ['cyclone', 'hurricane', 'spiral'],
    '💤': ['sleeping', 'symbol', 'zzz'],
    '🏧': ['atm', 'sign', 'bank'],
    '🚾': ['water', 'closet', 'wc'],
    '♿': ['wheelchair', 'symbol', 'accessibility'],
    '🅿️': ['parking', 'button', 'car'],
    '🈳': ['japanese', 'vacancy', 'button'],
    '🈂️': ['japanese', 'service', 'charge', 'button'],
    '🛂': ['passport', 'control', 'immigration'],
    '🛃': ['customs', 'baggage', 'claim'],
    '🛄': ['baggage', 'claim', 'airport'],
    '🛅': ['left', 'luggage', 'storage'],
    '🚹': ['mens', 'symbol', 'restroom'],
    '🚺': ['womens', 'symbol', 'restroom'],
    '🚼': ['baby', 'symbol', 'nursery'],
    '🚻': ['restroom', 'symbol', 'bathroom'],
    '🚮': ['litter', 'bin', 'symbol'],
    '🎦': ['cinema', 'symbol', 'movie'],
    '📶': ['antenna', 'bars', 'signal'],
    '🈁': ['japanese', 'here', 'button'],
    '🔣': ['input', 'symbol', 'numbers'],
    'ℹ️': ['information', 'source', 'info'],
    '🔤': ['input', 'latin', 'letters'],
    '🔡': ['input', 'latin', 'lowercase'],
    '🔠': ['input', 'latin', 'uppercase'],
    '🆖': ['ng', 'button', 'not', 'good'],
    '🆗': ['ok', 'button', 'alright'],
    '🆙': ['up', 'button', 'arrow'],
    '🆒': ['cool', 'button', 'awesome'],
    '🆕': ['new', 'button', 'fresh'],
    '🆓': ['free', 'button', 'gratis'],
    '0️⃣': ['digit', 'zero', 'number'],
    '1️⃣': ['digit', 'one', 'number'],
    '2️⃣': ['digit', 'two', 'number'],
    '3️⃣': ['digit', 'three', 'number'],
    '4️⃣': ['digit', 'four', 'number'],
    '5️⃣': ['digit', 'five', 'number'],
    '6️⃣': ['digit', 'six', 'number'],
    '7️⃣': ['digit', 'seven', 'number'],
    '8️⃣': ['digit', 'eight', 'number'],
    '9️⃣': ['digit', 'nine', 'number'],
    '🔟': ['keycap', 'ten', 'number'],
    '🔢': ['input', 'numbers', 'symbol'],
    '#️⃣': ['keycap', 'number', 'sign'],
    '*️⃣': ['keycap', 'asterisk', 'star'],
    '⏏️': ['eject', 'button', 'symbol'],
    '▶️': ['play', 'button', 'triangle'],
    '⏸️': ['pause', 'button', 'symbol'],
    '⏯️': ['play', 'pause', 'button'],
    '⏹️': ['stop', 'button', 'square'],
    '⏺️': ['record', 'button', 'circle'],
    '⏭️': ['next', 'track', 'button'],
    '⏮️': ['last', 'track', 'button'],
    '⏩': ['fast', 'forward', 'button'],
    '⏪': ['fast', 'reverse', 'button'],
    '⏫': ['fast', 'up', 'button'],
    '⏬': ['fast', 'down', 'button'],
    '◀️': ['reverse', 'button', 'triangle'],
    '🔼': ['upwards', 'button', 'triangle'],
    '🔽': ['downwards', 'button', 'triangle'],
    '➡️': ['right', 'arrow', 'direction'],
    '⬅️': ['left', 'arrow', 'direction'],
    '⬆️': ['up', 'arrow', 'direction'],
    '⬇️': ['down', 'arrow', 'direction'],
    '↗️': ['up', 'right', 'arrow'],
    '↘️': ['down', 'right', 'arrow'],
    '↙️': ['down', 'left', 'arrow'],
    '↖️': ['up', 'left', 'arrow'],
    '↕️': ['up', 'down', 'arrow'],
    '↔️': ['left', 'right', 'arrow'],
    '↪️': ['right', 'arrow', 'curving', 'left'],
    '↩️': ['left', 'arrow', 'curving', 'right'],
    '⤴️': ['right', 'arrow', 'curving', 'up'],
    '⤵️': ['right', 'arrow', 'curving', 'down'],
    '🔀': ['twisted', 'rightwards', 'arrows'],
    '🔁': ['repeat', 'button', 'arrows'],
    '🔂': ['repeat', 'single', 'button'],
    '🔄': ['counterclockwise', 'arrows', 'button'],
    '🔃': ['clockwise', 'vertical', 'arrows'],
    '🎵': ['musical', 'note', 'music'],
    '🎶': ['musical', 'notes', 'music'],
    '➕': ['plus', 'sign', 'add'],
    '➖': ['minus', 'sign', 'subtract'],
    '➗': ['division', 'sign', 'divide'],
    '✖️': ['multiplication', 'sign', 'multiply'],
    '♾️': ['infinity', 'symbol', 'endless'],
    '💲': ['heavy', 'dollar', 'sign'],
    '💱': ['currency', 'exchange', 'money'],
    '™️': ['trade', 'mark', 'symbol'],
    '©️': ['copyright', 'symbol', 'legal'],
    '®️': ['registered', 'symbol', 'legal'],
    '👁️‍🗨️': ['eye', 'speech', 'bubble'],
    '🔚': ['end', 'arrow', 'symbol'],
    '🔙': ['back', 'arrow', 'symbol'],
    '🔛': ['on', 'arrow', 'symbol'],
    '🔝': ['top', 'arrow', 'symbol'],
    '🔜': ['soon', 'arrow', 'symbol'],
    '〰️': ['wavy', 'dash', 'symbol'],
    '➰': ['curly', 'loop', 'symbol'],
    '➿': ['double', 'curly', 'loop'],
    '✔️': ['check', 'mark', 'symbol'],
    '☑️': ['check', 'box', 'mark'],
    '🔘': ['radio', 'button', 'symbol'],
    '🔴': ['red', 'circle', 'color'],
    '🟠': ['orange', 'circle', 'color'],
    '🟡': ['yellow', 'circle', 'color'],
    '🟢': ['green', 'circle', 'color'],
    '🔵': ['blue', 'circle', 'color'],
    '🟣': ['purple', 'circle', 'color'],
    '⚫': ['black', 'circle', 'color'],
    '⚪': ['white', 'circle', 'color'],
    '🟤': ['brown', 'circle', 'color'],
    '🔺': ['red', 'triangle', 'pointed', 'up'],
    '🔻': ['red', 'triangle', 'pointed', 'down'],
    '🔸': ['small', 'orange', 'diamond'],
    '🔹': ['small', 'blue', 'diamond'],
    '🔶': ['large', 'orange', 'diamond'],
    '🔷': ['large', 'blue', 'diamond'],
    '🔳': ['white', 'square', 'button'],
    '🔲': ['black', 'square', 'button'],
    '▪️': ['black', 'small', 'square'],
    '▫️': ['white', 'small', 'square'],
    '◾': ['black', 'medium', 'small', 'square'],
    '◽': ['white', 'medium', 'small', 'square'],
    '◼️': ['black', 'medium', 'square'],
    '◻️': ['white', 'medium', 'square'],
    '🟥': ['red', 'square', 'color'],
    '🟧': ['orange', 'square', 'color'],
    '🟨': ['yellow', 'square', 'color'],
    '🟩': ['green', 'square', 'color'],
    '🟦': ['blue', 'square', 'color'],
    '🟪': ['purple', 'square', 'color'],
    '⬛': ['black', 'large', 'square'],
    '⬜': ['white', 'large', 'square'],
    '🟫': ['brown', 'square', 'color'],
    '🔈': ['speaker', 'low', 'volume'],
    '🔇': ['muted', 'speaker', 'volume'],
    '🔉': ['speaker', 'medium', 'volume'],
    '🔊': ['speaker', 'high', 'volume'],
    '🔔': ['bell', 'notification', 'sound'],
    '🔕': ['bell', 'slash', 'mute'],
    '📣': ['megaphone', 'cheering', 'loudspeaker'],
    '📢': ['loudspeaker', 'announcement', 'public'],
    '👁️‍🗨️': ['eye', 'speech', 'bubble'],
    '💬': ['speech', 'balloon', 'talk'],
    '💭': ['thought', 'balloon', 'think'],
    '🗯️': ['right', 'anger', 'bubble'],
    '♠️': ['spade', 'suit', 'cards'],
    '♣️': ['club', 'suit', 'cards'],
    '♥️': ['heart', 'suit', 'cards'],
    '♦️': ['diamond', 'suit', 'cards'],
    '🃏': ['joker', 'playing', 'card'],
    '🎴': ['flower', 'playing', 'cards'],
    '🀄': ['mahjong', 'red', 'dragon'],

    // Flags
    '🏁': ['chequered', 'flag', 'racing'],
    '🚩': ['triangular', 'flag', 'red'],
    '🎌': ['crossed', 'flags', 'japan'],
    '🏴': ['black', 'flag', 'pirate'],
    '🏳️': ['white', 'flag', 'surrender'],
    '🏳️‍🌈': ['rainbow', 'flag', 'pride'],
    '🏳️‍⚧️': ['transgender', 'flag', 'pride'],
    '🏴‍☠️': ['pirate', 'flag', 'jolly', 'roger'],
    '🇦🇫': ['afghanistan', 'flag', 'country'],
    '🇦🇽': ['aland', 'islands', 'flag'],
    '🇦🇱': ['albania', 'flag', 'country'],
    '🇩🇿': ['algeria', 'flag', 'country'],
    '🇦🇸': ['american', 'samoa', 'flag'],
    '🇦🇩': ['andorra', 'flag', 'country'],
    '🇦🇴': ['angola', 'flag', 'country'],
    '🇦🇮': ['anguilla', 'flag', 'country'],
    '🇦🇶': ['antarctica', 'flag', 'continent'],
    '🇦🇬': ['antigua', 'barbuda', 'flag'],
    '🇦🇷': ['argentina', 'flag', 'country'],
    '🇦🇲': ['armenia', 'flag', 'country'],
    '🇦🇼': ['aruba', 'flag', 'country'],
    '🇦🇺': ['australia', 'flag', 'country'],
    '🇦🇹': ['austria', 'flag', 'country'],
    '🇦🇿': ['azerbaijan', 'flag', 'country'],
    '🇧🇸': ['bahamas', 'flag', 'country'],
    '🇧🇭': ['bahrain', 'flag', 'country'],
    '🇧🇩': ['bangladesh', 'flag', 'country'],
    '🇧🇧': ['barbados', 'flag', 'country'],
    '🇧🇾': ['belarus', 'flag', 'country'],
    '🇧🇪': ['belgium', 'flag', 'country'],
    '🇧🇿': ['belize', 'flag', 'country'],
    '🇧🇯': ['benin', 'flag', 'country'],
    '🇧🇲': ['bermuda', 'flag', 'country'],
    '🇧🇹': ['bhutan', 'flag', 'country'],
    '🇧🇴': ['bolivia', 'flag', 'country'],
    '🇧🇦': ['bosnia', 'herzegovina', 'flag'],
    '🇧🇼': ['botswana', 'flag', 'country'],
    '🇧🇷': ['brazil', 'flag', 'country'],
    '🇮🇴': ['british', 'indian', 'ocean', 'territory'],
    '🇻🇬': ['british', 'virgin', 'islands'],
    '🇧🇳': ['brunei', 'flag', 'country'],
    '🇧🇬': ['bulgaria', 'flag', 'country'],
    '🇧🇫': ['burkina', 'faso', 'flag'],
    '🇧🇮': ['burundi', 'flag', 'country'],
    '🇰🇭': ['cambodia', 'flag', 'country'],
    '🇨🇲': ['cameroon', 'flag', 'country'],
    '🇨🇦': ['canada', 'flag', 'country'],
    '🇮🇨': ['canary', 'islands', 'flag'],
    '🇨🇻': ['cape', 'verde', 'flag'],
    '🇧🇶': ['caribbean', 'netherlands', 'flag'],
    '🇰🇾': ['cayman', 'islands', 'flag'],
    '🇨🇫': ['central', 'african', 'republic'],
    '🇹🇩': ['chad', 'flag', 'country'],
    '🇨🇱': ['chile', 'flag', 'country'],
    '🇨🇳': ['china', 'flag', 'country'],
    '🇨🇽': ['christmas', 'island', 'flag'],
    '🇨🇨': ['cocos', 'islands', 'flag'],
    '🇨🇴': ['colombia', 'flag', 'country'],
    '🇰🇲': ['comoros', 'flag', 'country'],
    '🇨🇬': ['congo', 'brazzaville', 'flag'],
    '🇨🇩': ['congo', 'kinshasa', 'flag'],
    '🇨🇰': ['cook', 'islands', 'flag'],
    '🇨🇷': ['costa', 'rica', 'flag'],
    '🇨🇮': ['cote', 'divoire', 'flag'],
    '🇭🇷': ['croatia', 'flag', 'country'],
    '🇨🇺': ['cuba', 'flag', 'country'],
    '🇨🇼': ['curacao', 'flag', 'country'],
    '🇨🇾': ['cyprus', 'flag', 'country'],
    '🇨🇿': ['czechia', 'flag', 'country'],
    '🇩🇰': ['denmark', 'flag', 'country'],
    '🇩🇯': ['djibouti', 'flag', 'country'],
    '🇩🇲': ['dominica', 'flag', 'country'],
    '🇩🇴': ['dominican', 'republic', 'flag'],
    '🇪🇨': ['ecuador', 'flag', 'country'],
    '🇪🇬': ['egypt', 'flag', 'country'],
    '🇸🇻': ['el', 'salvador', 'flag'],
    '🇬🇶': ['equatorial', 'guinea', 'flag'],
    '🇪🇷': ['eritrea', 'flag', 'country'],
    '🇪🇪': ['estonia', 'flag', 'country'],
    '🇪🇹': ['ethiopia', 'flag', 'country'],
    '🇪🇺': ['european', 'union', 'flag'],
    '🇫🇰': ['falkland', 'islands', 'flag'],
    '🇫🇴': ['faroe', 'islands', 'flag'],
    '🇫🇯': ['fiji', 'flag', 'country'],
    '🇫🇮': ['finland', 'flag', 'country'],
    '🇫🇷': ['france', 'flag', 'country'],
    '🇬🇫': ['french', 'guiana', 'flag'],
    '🇵🇫': ['french', 'polynesia', 'flag'],
    '🇹🇫': ['french', 'southern', 'territories'],
    '🇬🇦': ['gabon', 'flag', 'country'],
    '🇬🇲': ['gambia', 'flag', 'country'],
    '🇬🇪': ['georgia', 'flag', 'country'],
    '🇩🇪': ['germany', 'flag', 'country'],
    '🇬🇭': ['ghana', 'flag', 'country'],
    '🇬🇮': ['gibraltar', 'flag', 'territory'],
    '🇬🇷': ['greece', 'flag', 'country'],
    '🇬🇱': ['greenland', 'flag', 'territory'],
    '🇬🇩': ['grenada', 'flag', 'country'],
    '🇬🇵': ['guadeloupe', 'flag', 'territory'],
    '🇬🇺': ['guam', 'flag', 'territory'],
    '🇬🇹': ['guatemala', 'flag', 'country'],
    '🇬🇬': ['guernsey', 'flag', 'territory'],
    '🇬🇳': ['guinea', 'flag', 'country'],
    '🇬🇼': ['guinea', 'bissau', 'flag'],
    '🇬🇾': ['guyana', 'flag', 'country'],
    '🇭🇹': ['haiti', 'flag', 'country'],
    '🇭🇳': ['honduras', 'flag', 'country'],
    '🇭🇰': ['hong', 'kong', 'sar', 'china'],
    '🇭🇺': ['hungary', 'flag', 'country'],
    '🇮🇸': ['iceland', 'flag', 'country'],
    '🇮🇳': ['india', 'flag', 'country'],
    '🇮🇩': ['indonesia', 'flag', 'country'],
    '🇮🇷': ['iran', 'flag', 'country'],
    '🇮🇶': ['iraq', 'flag', 'country'],
    '🇮🇪': ['ireland', 'flag', 'country'],
    '🇮🇲': ['isle', 'man', 'flag'],
    '🇮🇱': ['israel', 'flag', 'country'],
    '🇮🇹': ['italy', 'flag', 'country'],
    '🇯🇲': ['jamaica', 'flag', 'country'],
    '🇯🇵': ['japan', 'flag', 'country'],
    '🎌': ['japan', 'flag', 'crossed'],
    '🇯🇪': ['jersey', 'flag', 'territory'],
    '🇯🇴': ['jordan', 'flag', 'country'],
    '🇰🇿': ['kazakhstan', 'flag', 'country'],
    '🇰🇪': ['kenya', 'flag', 'country'],
    '🇰🇮': ['kiribati', 'flag', 'country'],
    '🇽🇰': ['kosovo', 'flag', 'country'],
    '🇰🇼': ['kuwait', 'flag', 'country'],
    '🇰🇬': ['kyrgyzstan', 'flag', 'country'],
    '🇱🇦': ['laos', 'flag', 'country'],
    '🇱🇻': ['latvia', 'flag', 'country'],
    '🇱🇧': ['lebanon', 'flag', 'country'],
    '🇱🇸': ['lesotho', 'flag', 'country'],
    '🇱🇷': ['liberia', 'flag', 'country'],
    '🇱🇾': ['libya', 'flag', 'country'],
    '🇱🇮': ['liechtenstein', 'flag', 'country'],
    '🇱🇹': ['lithuania', 'flag', 'country'],
    '🇱🇺': ['luxembourg', 'flag', 'country'],
    '🇲🇴': ['macao', 'sar', 'china'],
    '🇲🇰': ['north', 'macedonia', 'flag'],
    '🇲🇬': ['madagascar', 'flag', 'country'],
    '🇲🇼': ['malawi', 'flag', 'country']
}